name = "Publish (nightly)"

[on.push]
branches = ["dev"]

[jobs.publish]
name = "Publish for ${{ matrix.os }}"
runs-on = "${{ matrix.os }}"

[jobs.publish.strategy]
fail-fast = false

[[jobs.publish.strategy.matrix.include]]
os = "ubuntu-latest"
artifact_name = "ycc"
asset_name = "ycc-linux"

[[jobs.publish.strategy.matrix.include]]
os = "windows-latest"
artifact_name = "ycc.exe"
asset_name = "ycc.exe"

[[jobs.publish.strategy.matrix.include]]
os = "macos-latest"
artifact_name = "ycc"
asset_name = "ycc-macos"

[[jobs.publish.steps]]
uses = "actions/checkout@v3"

[[jobs.publish.steps]]
name = "Read Git Hash"
uses = "prompt/actions-commit-hash@v3"
id = "commit"

[[jobs.publish.steps]]
name = "Rust Nightly"
uses = "actions-rs/toolchain@v1"
[jobs.publish.steps.with]
toolchain = "nightly"
override = true


[[jobs.publish.steps]]
name = "Build"
run = "cargo build --release"

[[jobs.publish.steps]]
name = "Upload binaries to release"
uses = "svenstaro/upload-release-action@v2"
[jobs.publish.steps.with]
tag = "preview-${{ steps.commit.outputs.short }}"
asset_name = "${{ matrix.asset_name }}"
repo_token = "${{ secrets.GITHUB_TOKEN }}"
file = "target/release/${{ matrix.artifact_name }}"
prerelease = true
