name: Rust Test
on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Cargo Build
      run: cargo build --release
    - name: Find Release
      run: |
        cd target/release/
        ls
